[package]
name = "aoc"
version = "2024.12.25"
edition = "2021"
rust-version = "1.83"

[features]

[dependencies]
cached = "0.54.0"
regex = "1.11.1"
petgraph = "0.6"
colored = "2.0"
ndarray = "0.15.6"
itertools = "0.12.0"
rayon = "1.10"
rustc-hash = "2.0"
